// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package repository

import (
	"database/sql"

	"github.com/paulmach/orb"
)

type Party struct {
	ID            string
	UserID        string
	Title         string
	IsPublic      bool
	Location      orb.Point
	StreetAddress sql.NullString
	PostalCode    sql.NullString
	State         sql.NullString
	Country       sql.NullString
	StartDate     sql.NullTime
	EndDate       sql.NullTime
}
