// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package repository

import (
	"context"
)

type Querier interface {
	DeleteParty(ctx context.Context, arg DeletePartyParams) error
}

var _ Querier = (*Queries)(nil)
